version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - npm install
  pre_build:
    commands:
      - cat template.yml | grep 'CodeUri' | sed 's/CodeUri://' | sed 's/[\/ ]//g' | xargs -t -i sh -c "cd {}; npm install"
      - cat template.yml | grep 'CodeUri' | sed 's/CodeUri://' | sed 's/[\/ ]//g' | xargs -t -i sh -c "zip -qr ./zips/{} {};"
      - cat template.yml | grep 'CodeUri' | sed 's/CodeUri://' | sed 's/[\/ ]//g' | xargs -t -i sh -c "sed 's/{}/s3:\/\/lsv-structure\/{}/g' template.yml > template-export.yml"
  build:
    commands:
      - aws s3 sync ./zips/ s3://lsv-structure
  post_build:
    commands:
      #- sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' scripts/template-configuration.json

artifacts:
  type: zip
  files:
    - template-export.yml
    # - template-configuration.json

